version: '3.8'

services:
  speak-swift:
    build:
      context: ..
      dockerfile: ci_cd/Dockerfile
    ports:
      - "3000:80"
    container_name: speak-swift-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production 